# Introduction

```{r parte_1, include=FALSE}
#### Code I: Introduction ####
```

Skates represent a diverse group, widely distributed around the world, from shallow to near 2000 m depth (Priede _et al_. 2006). More than 90% of elasmobranch species inhabit deep waters on the continental shelves and slopes (Compagno 1990). According to Bustamante _et al_. (2014), at least 30 cartilaginous fishes inhabit (or did inhabit) on the continental shelf off central Chile. Evidence suggests an overall increase in skate species richness with increasing latitude and shark species depth down to 500 m. Understanding the ecological factors that condition the role of elasmobranchs in deep-water ecosystems is possible by describing the feeding habits of these predators. Indeed, skates play an essential role in transferring energy of benthic and demersal trophic webs (Wheterbee & Cortés 2004, Ebert & Bizarro 2007). Although the degree of foraging specialization of the group varies from specialists to generalist species, many deepwater skates feed primarily on decapod crustaceans and secondarily teleosts, with polychaetes and amphipods being relevant prey groups too (Ebert and Bizarro 2007).

The Dusky finless skate, _Gurgesiella furvescens_ de Buen (1959), has a distribution from the Galápagos in Ecuador to Valparaíso in Chile (Lamilla & Saez 2003). The southern boundary of the _G. furvescens_ distribution ends at 35ºS, which is coincident with the limit of the Peruvian biogeographic province (Pequeño & Lamilla 1993, Sielfeld & Vargas 1996, Bustamante _et al_. 2014). McEachran & Compagno (1979) point out a distribution between 400 and 960 m depth, while Yañez & Barbieri (1974) found the species between 351-600 m at 33ºS (Valparaíso), and Sielfeld & Vargas (1996) found _G. furvescens_ between 300 and 600 m depth. In general, the biological aspects of the genus Gurgesiella are poorly known, and _G. furvescens_ is a scarcely studied species (Lamilla 2004). According to McEachran & Compagno (1979), the maturity size is at 50.9-52 cm body length in males, and from 55.2 to 56.8 cm body length in females. Ñacari _et al_. (2018) described a new species of monogenean parasite of the deep-sea skate _G. furvescens_. In the Atlantic, there are two species _G. atlantica_ (Bigelow & Schroeder 1962) and _G. dorsalifera_ (McEachran & Compagno 1980). Rincón _et al_. (2008) described the trophic spectrum of _G. dorsalifera_ in southern Brazil. The analysis of stomach contents revealed apparent opportunistic predation on juveniles of _Urophycis brasiliensis_, followed by mysidaceans, unidentified teleosts, copepods, and decapod crustaceans.

In Chile, _G. furvescens_ is occasionally caught as bycatch in the trawl fisheries of benthic crustaceans (Acuña _et al_. 2005, Queirolo _et al_. 2011, Bustamante _et al_. 2014). The trawl fisheries are targeting two squat-lobsters (_Cervimunida johni_ and _Pleuroncodes monodon_), the shrimp _Heretocarpus reedi_, and occasionally the deepwater shrimp _Haliporoides diomedeae_ (Arana _et al_. 2003, Acuña _et al_. 2014). There is no published information about the diet of _G. furvescens_, and the objective of this paper was to study the diet of _G. furvescens_ and the relationships between prey size and mouth size of the predator, as well as the weight of the prey and the body weight of the predator.

