# Discussion

```{r parte_4, include=FALSE}
#### Code IV: Discussion ####
```

Acuña _et al_. (2005) and Bustamante _et al_. (2014) reported that _G. furvescens_ was in the by-catch of the benthic crustaceans fisheries, with low frequency. Indeed, in terms of relative frequency, Bustamante _et al_. (2014) reported a depth range between 362 and 484 m and a latitudinal range between 29.4 and 32ºS in 2006. In our results, the presence of _G. furvescens_ was low in the trawl nets, but the samples collected allow us to report wide, deep distribution from 179 to 511 m, as well as covering a higher latitudinal range than previously described (_i.e._, from 25.5°S to 33°S). On the other hand, the maximum size reported for _G. furvescens_ was 56.8 cm by Lamilla (Pers. Comments and unpublished data), but in the current study we found 5 larger individuals, the largest being 64.5 cm. Also, McEachran & Compagno (1979) mentioned that the male individuals of _G. furvescens_ reach maturity between 50.9 and 52.0 cm of total body length, this time, there is an individual of 48.6 cm already mature, and in the case of females, individuals mature from 44.3 cm.

The number of specimens was low ($n=51$), but this number seems to be enough to study the diet of _G. furvescens_. Indeed, the stomach contents revealed a minimal number of preys represented by _Heterocarpus reedi_, _Haliporoides diomedeae_, and indeterminate crustaceans. The latter were digested and probably parts of either _H. reedi_ or _H. diomedeae_. The Dusky finless skate seems to be more associated with the depth range of _H. reedi_, in which this prey is much more abundant. Although _G. furvescens_ was also caught in the bycatch of squat-lobsters (_Cervimunida johni_ and _Pleuroncodes monodon_), these crustaceans were not present in the stomach contents. Besided, we should mention that we found no more than one or two specimens in the stomach contents.

The feeding coefficient ($Q$) revealed a strong preference for _H. reedi_. Probably _G. furvescens_ is a specialist predator based on _H. reedi_. Besides, considering the low number of specimens per stomach, probably the energy requirement of _G. furvescens_ could be likely low. _H. reedi_ is an abundant and available prey for _G. furvescens_ and probably enough to meet its energy requirements. The depth range between the prey and the predator is overlapped, but the latitudinal distribution of _H. reedi_ extends to 37º10’S (Acuña _et al_. 2013), south of the latitudinal boundary of _G. furvescens_ (Pequeño & Lamilla 1993, Sielfeld & Vargas 1996). In this context, the southern limit of the distribution cannot be explained by its preference for feeding _H. reedi_.
The ratio between prey size and the mouth size of the predator was close to 1.47 at the 90% quantile. Because a prey tends to be larger than mouth size, probably shrimps are sucked by _G. furvescens_. According to Wilga _et al_. (2007), elasmobranchs specializing in suction-feeding are likely limited to bottom associated prey and because of their small gape may have a diet restricted to relatively small prey. In addition, the ratio between weight of preys and body weight tend to be constant, suggesting that large skates tend to eat larger preys.
